version: 2
updates:
  # Maintain dependencies for Maven in the v2.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven in the v2.0.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.0.x
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jooq:jooq"
        versions: ["[3.17,)"]

  # Maintain dependencies for Maven in the v1.15.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v1.15.x
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.dasniko:testcontainers-keycloak"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jooq:jooq"
        versions: ["[3.17,)"]

  # Maintain dependencies for Maven in the v1.14.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v1.14.x
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.dasniko:testcontainers-keycloak"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jooq:jooq"
        versions: ["[3.17,)"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "daily"

