version: 2
updates:
  # Maintain dependencies for Maven in the default branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven in the v2.0.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.0.x
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven in the v1.14.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v1.14.x
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.dasniko:testcontainers-keycloak"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Maven in the v1.13.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v1.13.x
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.dasniko:testcontainers-keycloak"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

